projeto/avalista/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from projeto.avalista import views as v

app_name='avalista' 

urlpatterns = [
    path('delete-avalista-esctop/<int:pk>/', login_required(v.EsctopAvalistaDelete.as_view()), name='esctop_avalista_delete'),
    path('detalhes-avalista-esctop/<int:pk>/', login_required(v.EsctopAvalistaDetail.as_view()), name='esctop_avalista_detail'),
    path('formulario-fiador-esctop/', login_required(v.EsctopAvalistaCreate.as_view()), name='esctop_avalista_create'),
    path('atualiza-avalista-esctop/<int:pk>/', login_required(v.EsctopFiadorUpdate.as_view()), name='esctop_avalista_update'),
    path('avalistas-esctop/', login_required(v.EsctopAvalistaList.as_view()), name='esctop_avalista_list'),
]

projeto/cliente/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from projeto.cliente import views as v

app_name='cliente' 

urlpatterns = [
    path('credcoop-escolha/', login_required(v.CredcoopClienteDecision.as_view()), name='credcoop_decision'),
    path('credcoop-delete/<int:pk>/', login_required(v.CredcoopClienteDelete.as_view()), name='credcoop_cliente_delete'),
    path('detalhes-cliente-credcoop/<int:pk>/', login_required(v.CredcoopClienteDetail.as_view()), name='credcoop_client_detail'),
    path('formulario-cliente-credcoop/', login_required(v.CredcoopClienteCreate.as_view()), name='credcoop_cliente_create'),
    path('atualiza-cliente-credcoop/<int:pk>/', login_required(v.CredcoopClienteUpdate.as_view()), name='credcoop_update'),
    path('clientes-credcoop/', login_required(v.CredcoopClienteList.as_view()), name='credcoop_cliente_list'),
    path('dashboard-credcoop/', login_required(v.CredcoopDashboard.as_view()), name='credcoop_dashboard'),

    # Fiador
    path('formulario-fiador-credcoop/', login_required(v.CredcoopFiadorCreate.as_view()), name='credcoop_fiador_create'),
]

projeto/cliente_cnpj/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from projeto.cliente_cnpj import views as v

app_name='cliente_cnpj'

urlpatterns = [
    path('esctop-escolha/', login_required(v.EsctopClienteDecision.as_view()), name='esctop_cliente_decision'),
    path('esctop-delete/<int:pk>/', login_required(v.EsctopClienteDelete.as_view()), name='esctop_delete'),
    path('detalhes-cliente-esctop/<int:pk>/', login_required(v.EsctopClienteDetail.as_view()), name='esctop_cliente_detail'),
    path('formulario-cliente-esctop/', login_required(v.EsctopClienteCreate.as_view()), name='esctop_cliente_create'),
    path('atualiza-cliente-esctop/<int:pk>/', login_required(v.EsctopClienteUpdate.as_view()), name='esctop_cliente_update'),
    path('clientes-esctop/', login_required(v.EsctopClientList.as_view()), name='esctop_cliente_list'),
    
    # APIS
    path('esctop-api/clientes/', login_required(v.EsctopClienteCreateAPI.as_view()), name='esctop_cliente_create_api'),
]

projeto/core/urls.py
from django.urls import path
from projeto.core import views as v
from projeto.core.views import SignUpView


app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('aniversariantes_lista/', v.aniversariantes, name='aniversariantes'),
    path('cliente_select/', v.cliente_select, name='cliente_select'),
    path('fiador_decision/', v.fiador_decision, name='fiador_decision'),
    path('fiador_decision_1/', v.fiador_decision_1, name='fiador_decision_1'),
    path('registro/', SignUpView.as_view(), name='register'),
]

projeto/emprestimo/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from projeto.emprestimo import views as v

app_name='emprestimo' 

urlpatterns = [

    # Credcoop
    path('formulario-emprestimo-credcoop/', login_required(v.CredcoopEmprestimoCreate.as_view()), name='credcoop_emprestimo_form'),
    path('emprestimos-credcoop/', login_required(v.CredcoopEmprestimoList.as_view()), name='credcoop_emprestimo_list'),

    # Credcoop Impressos
    path('<int:pk>/credcoop_promissoria/', login_required(v.CredcoopPromissoria.as_view()), name='credcoop_promissoria'),
    path('<int:pk>/credcoop_contrato/', login_required(v.CredcoopContrato.as_view()), name='credcoop_contrato'),
    path('<int:pk>/credcoop_contrato_e_promissoria/', login_required(v.CredcoopContratoPromissoria.as_view()), name='credcoop_contrato_e_promissoria'),

    # Esctop
    path('formulario-emprestimo-esctop/', login_required(v.EsctopEmprestimoCreate.as_view()), name='esctop_emprestimo_form'),
    path('emprestimos-esctop/', login_required(v.EsctopEmprestimoList.as_view()), name='esctop_emprestimo_list'),    
    
    # Esctop impressos
    path('<int:pk>/esctop_promissoria/', login_required(v.EsctopPromissoria.as_view()), name='esctop_promissoria'),
    path('<int:pk>/esctop_contrato/', login_required(v.EsctopContrato.as_view()), name='esctop_contrato'),
    path('<int:pk>/esctop_contrato_e_promissoria/', login_required(v.EsctopContratoPromissoria.as_view()), name='esctop_contrato_e_promissoria'),


    path('emprestimo-delete/<int:pk>/', login_required(v.EmprestimoDelete.as_view()), name='emprestimo_delete'),
    path('detalhes-emprestimo/<int:pk>/', login_required(v.EmprestimoDetail.as_view()), name='emprestimo_detail'),

    path('<int:pk>/pagamento_add/', v.emprestimo_pagamento_add, name='emprestimo_pagamento_add'),
    path('<int:pk>/pagamento/', v.emprestimo_pagamento, name='emprestimo_pagamento'),
    path('<int:pk>/pagamento_list/', v.emprestimo_pagamento_list, name='emprestimo_pagamento_list'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    # project
    path('api/', include('projeto.public.urls')),
    path('accounts/', include('projeto.accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('emprestimo/', include('projeto.emprestimo.urls')),   
    path('estoque/', include('projeto.estoque.urls')),
    path('credcoop/', include('projeto.cliente.urls')),
    path('esctop/', include('projeto.cliente_cnpj.urls')),
    path('avalista/', include('projeto.avalista.urls')),
    path('accounts-user/', include('django.contrib.auth.urls')),
    
    # Files
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
    # API
    path('api/auth/', include('rest_framework.urls'))
]

projeto/core/models.py
from django.db import models

class TimeStampedModel(models.Model):
    created = models.DateTimeField("criado em", auto_now=True, auto_now_add=False)
    modified = models.DateTimeField("Modificado em", auto_now=False, auto_now_add=True)
    
    class Meta:
        abstract = True


class Banco(models.Model):
    banco         = models.CharField("Banco", max_length=25, blank=True, null=True)   

    class Meta:
        ordering = ('banco',)
    
    def __str__(self):
        return str(self.banco)
        
        
class Tipo_de_conta(models.Model):
    tipo_de_conta = models.CharField("tipo_de_conta", max_length=25, blank=True, null=True)   

    class Meta:
        ordering = ('tipo_de_conta',)
    
    def __str__(self):
        return str(self.tipo_de_conta)
    
    
class Chave_PIX(models.Model):       
    pix_key_type = models.CharField("Tipo de Chave PIX", max_length=30, blank=True, null=True)
    
    class Meta:
        ordering = ('pix_key_type',)
        verbose_name = 'Tipo de Chave PIX'
        verbose_name_plural = 'Tipo de Chave PIX'

    def __str__(self):
        return str(self.pix_key_type)

projeto/core/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

projeto/core/views.py
from datetime import date

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from django.views.generic import TemplateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from projeto.cliente.models import Cliente
from projeto.cliente_cnpj.models import Cliente_cnpj
from projeto.avalista.models import Avalista

from itertools import chain


class Index(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'
    
    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        
        aniversariantes_credcoop = Cliente.objects.filter(
            data_nasc__month=date.today().month,
            data_nasc__day=date.today().day
        )

        aniversariantes_representante_esctop = Cliente_cnpj.objects.filter(
            rep_data_nasc__month=date.today().month,
            rep_data_nasc__day=date.today().day
        )

        aniversariantes_fiador_esctop = Avalista.objects.filter(
            fiador_data_nasc__month=date.today().month,
            fiador_data_nasc__day=date.today().day
        )

        total_aniversariantes = aniversariantes_credcoop.count() + aniversariantes_representante_esctop.count() + aniversariantes_fiador_esctop.count()
        context['total_aniversariantes'] = total_aniversariantes

        return context




class Aniversariantes(LoginRequiredMixin, TemplateView):
    template_name = 'aniversariantes_lista.html'

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super(Aniversariantes, self).get_context_data(**kwargs)

        aniversariantes_credcoop = Cliente.objects.filter(
            data_nasc__month=date.today().month,
            data_nasc__day=date.today().day
        )

        aniversariantes_representante_esctop = Cliente_cnpj.objects.filter(
            rep_data_nasc__month=date.today().month,
            rep_data_nasc__day=date.today().day
        )

        aniversariantes_fiador_esctop = Avalista.objects.filter(
            fiador_data_nasc__month=date.today().month,
            fiador_data_nasc__day=date.today().day
        )

        result_list = list(chain(aniversariantes_credcoop, aniversariantes_representante_esctop, aniversariantes_fiador_esctop))
        
        context['aniversariantes'] = result_list

        return context


@login_required
def cliente_select(request):
    return render(request, 'cliente_select.html')


@login_required
def fiador_decision(request):
    return render(request, 'fiador_decision.html')


@login_required
def fiador_decision_1(request):
    return render(request, 'fiador_decision_1.html')

index = Index.as_view()
aniversariantes = Aniversariantes.as_view()

projeto/core/templates/includes/footer.html
<style>
    header,
    section,
    footer {
        display: block;
    }

    html,
    body {
        margin: 0;
        padding: 0;
        height: 100%;
        margin-top: 40px;
    }

    body {
        width: 100%;
        display: -moz-box;
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;

        -moz-box-orient: vertical;
        -webkit-box-orient: vertical;
        -moz-box-direction: normal;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        -webkit-flex-direction: column;
        flex-direction: column;
    }

    section {
        -moz-box-flex: 1;
        -webkit-box-flex: 1;
        -ms-flex: 1;
        -webkit-flex: 1;
        flex: 1;
        background: #fff;
    }

    footer {
        background-image: linear-gradient(15deg, #2C3D4E 0%, #5eaa84 100%);
    }
</style>

<section></section>
{%load static%}
<footer class="d-flex flex-lg-row flex-column text-lg-start text-center" style="background-color: #7edffb;">
    <div class="container d-flex flex-lg-row flex-column py-lg-10 py-5 align-items-center gy-2">

        <div class="container mb-lg-0 mb-5 d-flex flex-column">
            <h6 class="text-white fs-20 lh-1">© 2023 Esctop Todos os direitos reservados</h6>
        </div>
    </div>

</footer>

projeto/core/templates/includes/nav.html
<html>
<style>
	body {
		margin: 0;
		font-family: Arial, Helvetica, sans-serif;
		margin-top: 65px;
		/* text-transform: uppercase; */
	}
	.navbar {
		font-family: Noto Sans, sans-serif;
		background-image: linear-gradient(15deg, #2C3D4E 0%, #5eaa84 100%);
		font-weight: bold;
	}
	.navbar-light .navbar-brand {
		color: rgb(255, 255, 255);		
		opacity: 1.0;
	}
	.navbar-light .navbar-nav .nav-link {
		color: rgb(255, 255, 255) !important;		
		opacity: 1.0;
	}
	
	.dropdown-item{
		opacity: 1.0;
	}
	.dropdown-item:hover {
		background-color: #2C3D4E !important;
		color: white
	}

	a .nav-link{
		left: auto !important;
		right: 0px;
	}	

	.navbar-nav li:hover > ul.dropdown-menu {
		display: block;
	}
	.dropdown-submenu {
		position:relative;
	}
	.dropdown-submenu>.dropdown-menu {
		top:0;
		left:100%;
		margin-top:-6px;
	}
	
	/* rotate caret on hover */
	.dropdown-menu > li > a:hover:after {
		text-decoration: underline;
		transform: rotate(-90deg);
	} 
	

	
	
</style>

<head>
	<nav class="navbar fixed-top navbar-expand-md navbar-light">
		<a class="navbar-brand pb-2" href="{% url 'core:index' %}">INÍCIO</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNavDropdown">
			<ul class="navbar-nav ">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" style="text-transform: uppercase;" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Cadastro
					</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">						
						<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">CLIENTES</a>
							<ul class="dropdown-menu">
								<li>
									<a class="dropdown-item" href="{% url 'cliente:credcoop_decision' %}">
										CREDCOOP
									</a>
								</li>
								<li>
									<a class="dropdown-item" href="{% url 'cliente_cnpj:esctop_cliente_decision' %}">
										ESCTOP
									</a>
								</li>
							</ul>
						</li>
						<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">FIADOR</a>
							<ul class="dropdown-menu">
								<li>
									<a class="dropdown-item" href="{% url 'avalista:esctop_avalista_create' %}">
										ESCTOP
									</a>
								</li>
							</ul>
						</li>
						<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">EMPRÉSTIMOS</a>
							<ul class="dropdown-menu">
								<li>
									<a class="dropdown-item" href="{% url 'emprestimo:credcoop_emprestimo_form' %}">CREDCOOP</a></li>
								<li><a class="dropdown-item" href="{% url 'emprestimo:esctop_emprestimo_form' %}">ESCTOP</a></li>
							</ul>
						</li>
					</ul>
				</li>

				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" style="text-transform: uppercase;" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Consulta
					</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">						
						<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">CLIENTES</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="{% url 'cliente:credcoop_cliente_list' %}">CREDCOOP</a></li>
								<li><a class="dropdown-item" href="{% url 'cliente_cnpj:esctop_cliente_list' %}">ESCTOP</a></li>
							</ul>
						</li>
						<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">FIADOR</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="{% url 'avalista:esctop_avalista_list' %}">ESCTOP</a></li>								
							</ul>
						</li>
						<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">EMPRÉSTIMOS</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" href="{% url 'emprestimo:credcoop_emprestimo_list' %}">CREDCOOP</a></li>
								<li><a class="dropdown-item" href="{% url 'emprestimo:esctop_emprestimo_list' %}">ESCTOP</a></li>
							</ul>
						</li>
					</ul>
				</li>
				
				<li class="nav-item dropdown">
					<a class=" nav-link dropdown-toggle" style="text-transform: uppercase;" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Usuário
					</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
						<li><a class="dropdown-item" href="{% url 'logout' %}">ENCERRAR SESSÃO</a></li>
					</ul>
				</li>	
			</ul>
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
					<a class="nav-link disabled" style=" color: rgb(240, 246, 255);">Olá, {{user.first_name}}!</a>
				{% endif %}
			</ul>
		</div>
	</nav>

</head>

<script>
	$(document).ready(function () {
		$('.dropdown-submenu a.dropdown-toggle').on("click", function (e) {
			console.log("This",e )
			if ($(this).next('ul').hasClass('show')) {
				$(this).next('ul').removeClass('show');
				$(this).parent().removeClass('show');
			} else {
				$(this).parents('.dropdown-menu').first().find('.show').removeClass('show');
				$(this).next('ul').toggleClass('show');
				$(this).parent().toggleClass('show');
				$(this).parent().siblings().removeClass('show');
			}
			e.stopPropagation();
			e.preventDefault();
		});
	});
	
</script>
</html>

projeto/core/templates/includes/pagination.html
<style>
    .pagination {
        display: inline-block;
    }

    .pagination a {
        color: black;
        float: left;
        padding: 8px 16px;
        text-decoration: none;
    }
</style>

<hr>
<div class="row">
    <div class="col-sm-6 text-center">
        <div class="dataTables_info" id="dataTable1_info" role="status" aria-live="polite">
            Mostrando {{ page_obj.start_index }} até {{ page_obj.end_index }} de {{ page_obj.paginator.count }} registros
        </div>

    </div>
    <div class="col-sm-6">
        <span class="pagination">
            {% if page_obj.has_previous %}
                <span class="paginate_button page-item active">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                </span>
            {% endif %}
            {% if page_obj.paginator.num_pages < 12 %}
                {% for page in page_obj.paginator.page_range %}
                <span class="paginate_button page-item {% if page_obj.number == page %}active{% endif %}">
                    <a class="page-link" href="?q={{ query }}&page={{ page }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ page }}</a>
                </span>
                {% endfor %}
            {% else %}
                {% if page_obj.number >= 1 and page_obj.number < 5 %}
                {% for page in page_obj.paginator.page_range %}
                    {% if page <= 5 %}
                    <span class="paginate_button page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link" href="?q={{query}}&page={{ page }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ page }}</a>
                    </span>
                    {% endif %}
                {% endfor %}
                <span class="paginate_button page-item disabled">
                    <a class="page-link">...</a>
                </span>
                <span class="paginate_button page-item
                    {% if page_obj.number == page_obj.paginator.num_pages %}
                    active
                    {% endif %}">
                    <a class="page-link" href="?q={{ query }}&page={{ page_obj.paginator.num_pages }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">
                    {{ page_obj.paginator.num_pages }}
                    </a>
                </span>
                {% elif page_obj.number >= 5 and page_obj.number < page_obj.paginator.num_pages|add:"-3" %}
                <span class="paginate_button page-item {% if page_obj.number == page %}active{% endif %}">
                    <a class="page-link" href="?page=1{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">1</a>
                </span>
                <span class="paginate_button page-item disabled">
                    <a class="page-link">...</a>
                </span>
                {% for page in page_obj.paginator.page_range %}
                    {% if page == page_obj.number %}
                    <span class="paginate_button page-item {% if page_obj.number == page_obj.previous_page_number %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ page_obj.previous_page_number }}</a>
                    </span>
                    <span class="paginate_button page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link" href="?q={{query}}&page={{ page }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ page }}</a>
                    </span>
                    <span class="paginate_button page-item {% if page_obj.number == page_obj.next_page_number %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ page_obj.next_page_number }}</a>
                    </span>
                    {% endif %}
                {% endfor %}
                <span class="paginate_button page-item disabled">
                    <a class="page-link">...</a>
                </span>
                <span class="paginate_button page-item
                    {% if page_obj.number == page_obj.paginator.num_pages %}
                    active
                    {% endif %}">
                    <a class="page-link" href="?q={{ query }}&page={{ page_obj.paginator.num_pages }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">
                    {{ page_obj.paginator.num_pages }}
                    </a>
                </span>
                {% elif page_obj.paginator.num_pages|add:"-3" >= 1 and page_obj.number <= page_obj.paginator.num_pages %}
                <span class="paginate_button page-item {% if page_obj.number == page %}active{% endif %}">
                    <a class="page-link" href="?page=1{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">1</a>
                </span>
                <span class="paginate_button page-item disabled">
                    <a class="page-link">...</a>
                </span>
                {% for page in page_obj.paginator.page_range %}
                    {% if page >= page_obj.paginator.num_pages|add:"-4" %}
                    <span class="paginate_button page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link" href="?q={{query}}&page={{ page }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ page }}</a>
                    </span>
                    {% endif %}
                {% endfor %}
                {% endif %}
            {% endif %}
            {% if page_obj.has_next %}
                <span class="paginate_button page-item active">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a>
                </span>
            {% endif %}
        </span>
        
    </div>
</div>
    