projeto/cliente/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from projeto.cliente import views as v

app_name='cliente' 

urlpatterns = [
    path('credcoop-escolha/', login_required(v.CredcoopClienteDecision.as_view()), name='credcoop_decision'),
    path('credcoop-delete/<int:pk>/', login_required(v.CredcoopClienteDelete.as_view()), name='credcoop_cliente_delete'),
    path('detalhes-cliente-credcoop/<int:pk>/', login_required(v.CredcoopClienteDetail.as_view()), name='credcoop_client_detail'),
    path('formulario-cliente-credcoop/', login_required(v.CredcoopClienteCreate.as_view()), name='credcoop_cliente_create'),
    path('atualiza-cliente-credcoop/<int:pk>/', login_required(v.CredcoopClienteUpdate.as_view()), name='credcoop_update'),
    path('clientes-credcoop/', login_required(v.CredcoopClienteList.as_view()), name='credcoop_cliente_list'),
    path('dashboard-credcoop/', login_required(v.CredcoopDashboard.as_view()), name='credcoop_dashboard'),

    # Fiador
    path('formulario-fiador-credcoop/', login_required(v.CredcoopFiadorCreate.as_view()), name='credcoop_fiador_create'),
]

projeto/cliente_cnpj/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from projeto.cliente_cnpj import views as v

app_name='cliente_cnpj'

urlpatterns = [
    path('esctop-escolha/', login_required(v.EsctopClienteDecision.as_view()), name='esctop_cliente_decision'),
    path('esctop-delete/<int:pk>/', login_required(v.EsctopClienteDelete.as_view()), name='esctop_delete'),
    path('detalhes-cliente-esctop/<int:pk>/', login_required(v.EsctopClienteDetail.as_view()), name='esctop_cliente_detail'),
    path('formulario-cliente-esctop/', login_required(v.EsctopClienteCreate.as_view()), name='esctop_cliente_create'),
    path('atualiza-cliente-esctop/<int:pk>/', login_required(v.EsctopClienteUpdate.as_view()), name='esctop_cliente_update'),
    path('clientes-esctop/', login_required(v.EsctopClientList.as_view()), name='esctop_cliente_list'),
    
    # APIS
    path('esctop-api/clientes/', login_required(v.EsctopClienteCreateAPI.as_view()), name='esctop_cliente_create_api'),
]

projeto/core/urls.py
from django.urls import path
from projeto.core import views as v
from projeto.core.views import SignUpView


app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('aniversariantes_lista/', v.aniversariantes, name='aniversariantes'),
    path('cliente_select/', v.cliente_select, name='cliente_select'),
    path('fiador_decision/', v.fiador_decision, name='fiador_decision'),
    path('fiador_decision_1/', v.fiador_decision_1, name='fiador_decision_1'),
    path('registro/', SignUpView.as_view(), name='register'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    # project
    path('api/', include('projeto.public.urls')),
    path('accounts/', include('projeto.accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('emprestimo/', include('projeto.emprestimo.urls')),   
    path('estoque/', include('projeto.estoque.urls')),
    path('credcoop/', include('projeto.cliente.urls')),
    path('esctop/', include('projeto.cliente_cnpj.urls')),
    path('avalista/', include('projeto.avalista.urls')),
    path('accounts-user/', include('django.contrib.auth.urls')),
    
    # Files
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
    # API
    path('api/auth/', include('rest_framework.urls'))
]

projeto/core/models.py
from django.db import models

class TimeStampedModel(models.Model):
    created = models.DateTimeField("criado em", auto_now=True, auto_now_add=False)
    modified = models.DateTimeField("Modificado em", auto_now=False, auto_now_add=True)
    
    class Meta:
        abstract = True


class Banco(models.Model):
    banco         = models.CharField("Banco", max_length=25, blank=True, null=True)   

    class Meta:
        ordering = ('banco',)
    
    def __str__(self):
        return str(self.banco)
        
        
class Tipo_de_conta(models.Model):
    tipo_de_conta = models.CharField("tipo_de_conta", max_length=25, blank=True, null=True)   

    class Meta:
        ordering = ('tipo_de_conta',)
    
    def __str__(self):
        return str(self.tipo_de_conta)
    
    
class Chave_PIX(models.Model):       
    pix_key_type = models.CharField("Tipo de Chave PIX", max_length=30, blank=True, null=True)
    
    class Meta:
        ordering = ('pix_key_type',)
        verbose_name = 'Tipo de Chave PIX'
        verbose_name_plural = 'Tipo de Chave PIX'

    def __str__(self):
        return str(self.pix_key_type)

projeto/core/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

projeto/core/views.py
from datetime import date

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from django.views.generic import TemplateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from projeto.cliente.models import Cliente
from projeto.cliente_cnpj.models import Cliente_cnpj
from projeto.avalista.models import Avalista

from itertools import chain


class Index(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'
    
    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        
        aniversariantes_credcoop = Cliente.objects.filter(
            data_nasc__month=date.today().month,
            data_nasc__day=date.today().day
        )

        aniversariantes_representante_esctop = Cliente_cnpj.objects.filter(
            rep_data_nasc__month=date.today().month,
            rep_data_nasc__day=date.today().day
        )

        aniversariantes_fiador_esctop = Avalista.objects.filter(
            fiador_data_nasc__month=date.today().month,
            fiador_data_nasc__day=date.today().day
        )

        total_aniversariantes = aniversariantes_credcoop.count() + aniversariantes_representante_esctop.count() + aniversariantes_fiador_esctop.count()
        context['total_aniversariantes'] = total_aniversariantes

        return context




class Aniversariantes(LoginRequiredMixin, TemplateView):
    template_name = 'aniversariantes_lista.html'

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super(Aniversariantes, self).get_context_data(**kwargs)

        aniversariantes_credcoop = Cliente.objects.filter(
            data_nasc__month=date.today().month,
            data_nasc__day=date.today().day
        )

        aniversariantes_representante_esctop = Cliente_cnpj.objects.filter(
            rep_data_nasc__month=date.today().month,
            rep_data_nasc__day=date.today().day
        )

        aniversariantes_fiador_esctop = Avalista.objects.filter(
            fiador_data_nasc__month=date.today().month,
            fiador_data_nasc__day=date.today().day
        )

        result_list = list(chain(aniversariantes_credcoop, aniversariantes_representante_esctop, aniversariantes_fiador_esctop))
        
        context['aniversariantes'] = result_list

        return context


@login_required
def cliente_select(request):
    return render(request, 'cliente_select.html')


@login_required
def fiador_decision(request):
    return render(request, 'fiador_decision.html')


@login_required
def fiador_decision_1(request):
    return render(request, 'fiador_decision_1.html')

index = Index.as_view()
aniversariantes = Aniversariantes.as_view()

projeto/core/templates/aniversariantes_lista.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'bootstrap/css/jquery.datatables.min.css' %}" rel="stylesheet">
<link href="{% static 'bootstrap/css/responsive.datatables.min.css' %}" rel="stylesheet">

<style>    
    .dataTables_length, .dataTables_filter{
        display: none;
    }

</style>
{% endblock css %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Início</a></li>
            <li class="breadcrumb-item active" aria-current="page">Lista de aniversariantes</li>
        </ol>
    </nav>

    <hr class="mg-t-50 mg-b-40">
    <div class="card card-body">        
        <h4 id="section2" class="mg-b-10">Aniversariantes do dia</h4>
        <p class="mg-b-30">Lista com todos os aniversariantes do dia de hoje</p>
        <div data-label="Example" class="df-example demo-table">
            {% if aniversariantes %}
            <table id="example2" class="table table-hover mg-b-0">
                <thead>
                    <tr>
                        <th class="wd-10p">Nome</th>
                    </tr>
                </thead>
                <tbody>
                    {% for aniversariante in aniversariantes %}
                        <tr class="text-uppercase">                                
                            {% if aniversariante.nome %}
                                <td>{{aniversariante.nome}} <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#staticBackdrop{{ forloop.counter }}">Ver contatos</button></td>
                            {% elif aniversariante.razao_social %}
                                <td>{{aniversariante.razao_social}} <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#staticBackdrop{{ forloop.counter }}">Ver contatos</button></td>
                            {% else %}
                                <td >{{aniversariante.fiador_nome}} <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#staticBackdrop{{ forloop.counter }}">Ver contatos</button></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>
    <hr class="mg-t-50 mg-b-40">

    <!-- Modal -->
    {% for aniversariante in aniversariantes %}
        <div class="modal fade" id="staticBackdrop{{ forloop.counter }}" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdrop{{ forloop.counter }}Label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdrop{{ forloop.counter }}Label">Contatos do cliente</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                        <tr class="text-uppercase">
                            <!-- Cliente Credcoop -->
                            {% if aniversariante.nome %}
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">{{aniversariante.nome}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if aniversariante.contato1 %}
                                        <tr>
                                            <td>
                                                <label>Contato 1</label>
                                                <h5>{{aniversariante.contato1}}</h5>
                                            </td>
                                        </tr>
                                    {% endif %}
                                    {% if aniversariante.contato2 %}
                                        <tr>
                                            <td>
                                                <label>Contato 2</label>
                                                <h5>{{aniversariante.contato2}}</h5>
                                            </td>
                                        </tr>
                                    {% endif %}
                                    {% if aniversariante.celular1 %}
                                        <tr>
                                            <td>
                                                <label>Celular 1</label>
                                                <h5>{{aniversariante.celular1}}</h5>
                                            </td>
                                        </tr>
                                    {% endif %}
                                    {% if aniversariante.celular2 %}
                                        <tr>
                                            <td>
                                                <label>Celular 2</label>
                                                <h5>{{aniversariante.celular2}}</h5>
                                            </td>
                                        </tr>
                                    {% endif %}
                                </tbody>
                            </table>
                            {% elif aniversariante.razao_social %}
                                <h5>2</h5>
                            {% else %}
                                <h5>3</h5>
                            {% endif %}
                        </tr>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock content %}

{% block js %}

<script src="{% static 'bootstrap/js/jquery.datatables.min.js' %}"></script>
<script src="{% static 'bootstrap/js/datatables.datatables.min.js' %}"></script>
<script src="{% static 'bootstrap/js/datatables.responsive.min.js' %}"></script>
<script src="{% static 'bootstrap/js/responsive.datatables.min.js' %}"></script>

<script>
    $('#example2').DataTable({
        responsive: true,
        language: {
            searchPlaceholder: 'Buscar...',
            sSearch: '',
            lengthMenu: '_MENU_ items/page',
            info: "Mostrando _PAGE_ de _PAGES_ paginas",
        }
    });    
</script>
{% endblock js %}

projeto/core/templates/base.html
<!doctype html>
<html lang="pt-br">
{% load static %}
{% load widget_tweaks %}

<head>
  <!-- Required meta tags -->  
  <script src="{% static 'bootstrap/js/jquery-1.11.2.js' %}"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=0.8, shrink-to-fit=no">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">

  <title>ESCTOP - SISTEMA</title>

  <!-- Bootstrap CSS -->  
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" >
  
  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  {% comment %} Comentei o font-awesome abaixo para observar se não afeta 
  nenhuma tela para depois remover. será substituido pelo estilo acima. Remover o font-awesome antigo também {% endcomment %}
  {% comment %} <link rel="stylesheet" href="{% static 'bootstrap/css/font-awesome.min.css' %}"> {% endcomment %}

  <!-- Select2 -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/select2.min.css' %}" />

  <!-- MEUS CSS -->
  {% block css %}{% endblock css %}
  <style>
    .select2-container .select2-selection--single {
      height: 31px !important;
    }
    .ok {
      color: green;
    }

    .no {
      color: red;
    }

    label.required:after {
      content: "*";
      color: red;
    }

    label {
      font-weight: bold;
      margin-bottom: 0px;
    }

    /* todas as letras maiusculas */
    .upper_all {
      text-transform: uppercase;
    }

    .lower_all {
      text-transform: lowercase;
    }

    /* STYLE DE CONTENT E TABS DOS TEMPLATES DE CADASTRO */
    body {
      font-family: Arial;
      {% comment %} background-color: #5eaa8449; {% endcomment %}
      {% comment %} background: url("{% static 'imagens/fundo.jpg' %}"); {% endcomment %}
      {% comment %} background-attachment: fixed; {% endcomment %}
      
    }

    /* Style the tab */
    .tab {
      /* overflow: hidden; */
      border: 1px solid #ccc;
      background-color: #f1f1f1;
      border-top: 0px;
      /* position: fixed; */
      z-index: 1;
      top: 53px;
      /* width: 1109px; */
    }

    /* Style the buttons inside the tab */
    .tab button {
      background-color: inherit;
      float: left;
      border: none;
      outline: none;
      cursor: pointer;
      padding: 14px 16px;
      /*transition: 0.3s;*/
      font-size: 17px;
    }

    /* Change background color of buttons on hover */
    .tab button:hover {
      background-color: #ddd;
    }

    /* Create an active/current tablink class */
    .tab button.active {
      background-color: #ccc;
    }

    /* Style the tab content */
    .tabcontent {
      display: none;
      padding: 6px 12px;
      border: 1px solid #ccc;
      border-top: none;
      margin-top: 45px;
      -webkit-animation: fadeEffect 1s;
      z-index: -1;
    }

    /* Fade in tabs */
    @-webkit-keyframes fadeEffect {
      from {
        opacity: 0;
      }

      to {
        opacity: 1;
      }
    }

    @keyframes fadeEffect {
      from {
        opacity: 0;
      }

      to {
        opacity: 1;
      }
    }

    /* STYLE DE CONTENT E TABS DOS TEMPLATES DE CADASTRO */

    /*ESTILO DAS LISTAS*/
    .maiusculo {
      text-transform: uppercase;
    }

    /*ESTILO DAS LISTAS*/

    /* ESTILOS DAS TELAS DE IMPRESSÃO DE DETALHES DE CLIENTE */
    .color {
      background-color: rgb(156, 156, 156);
    }

    @media print {

      .no-print,
      .no-print * {
        display: none !important;
      }

      @page {
        margin: 0.5cm;
      }

      label {
        font-size: 9pt;
        padding: 0px;
      }

      h2 {
        font-weight: bold;
        padding: 0px;
        font-size: 13pt;
      }

      div {
        columns: 90px 1;
        margin: 0px, 0px, 0px, 0px;
      }

      @media all {
        .page-break {
          display: none;
        }
      }

      @media print {
        .page-break {
          display: block;
          page-break-before: always;
        }
      }
    }

    div.a {
      text-transform: uppercase;
    }

    .noHover{
      pointer-events: none;
    }

    .form-control:focus {
      color: #495057;
      background-color: #fff;
      border-color: #5eaa84 !important;
      outline: 0;
      box-shadow: none !important;
      border-width: 2px;
    }

    a {
      text-decoration: none !important;
    }
    
  </style>
  <!-- MEUS CSS -->
  
</head>

<body>
  {% if user.is_authenticated %}
  {% include "includes/nav.html" %}
  {% endif %}
  
  <div id="app" class="container pb-3 mb-5">
    {% block content %}{% endblock content %}
  </div>
  
  {% if user.is_authenticated %}
  {% include "includes/footer.html" %}
  {% endif %}
  
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  
  {% block js %}{% endblock js %}

  <script type="text/javascript">
    
    /*OCULTA FORMULÁRIOS NA TELA DE CADASTRO DE CLIENTES - TABCONTENTS*/
    function openCity(evt, cityName) {
      var i, tabcontent, tablinks;
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
      }
      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      document.getElementById(cityName).style.display = "block";
      evt.currentTarget.className += " active";
    }
    /*OCULTA FORMULÁRIOS NA TELA DE CADASTRO DE CLIENTES - TABCONTENTS*/
    
  </script>

  <script type="text/javascript" src="{% static 'bootstrap/js/jquery-3.5.1.slim.min.js' %}" ></script>
  <script type="text/javascript" src="{% static 'bootstrap/js/popper.min.js' %}" ></script>
  <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}" ></script>
  <script type="text/javascript" src="{% static 'bootstrap/js/jquery-3.3.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap/js/masks.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap/js/jquery.mask.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap/js/jquery-ui.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap/js/jquery.mask.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap/js/select2.min.js' %}"></script>

</body>

</html>

projeto/core/templates/base_impressoes_refatorado.html
<!doctype html>
<html lang="pt-br">
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <title>{{object.cliente_cnpj.razao_social}}</title>

    {% block css %}{% endblock css %}

    <style type="text/css">
        .pageBreak {
            page-break-after: always;
        }
        .row {
            margin: 0;
            padding: 0;
        }
        body {
            counter-reset: section;
        }
        @media print {
            h3 {
                position: absolute;
                page-break-before: always;
                page-break-after: always;
                bottom: 0;
                right: 0;
                font-size: 1.5rem;
            }

            h3::before {
                position: relative;
                bottom: 0px;
                counter-increment: section;
                content: counter(section);
            }
            
        }
    </style>
</head>

<body>

    <div id="app">
        {% block content %}{% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    {% block js %}{% endblock js %}
</body>

</html>

projeto/core/templates/cliente_select.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid shadow rounded">
        <div class="container">
            <h1>Escolha um Cliente</h1>           

            <span class="pull-center">
                <a href="{% url 'cliente:credcoop_cliente_list' %}" type="button" class="btn btn-secondary">CPF</a>                
                <a href="{% url 'cliente_cnpj:esctop_cliente_list' %}" type="button" class="btn btn-secondary">CNPJ</a>
            </span>            
        </div>        
    </div>
{% endblock content %}

projeto/core/templates/index.html
{% extends 'base.html' %}

{% block css %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<style>
    .card {
        min-height:125px;
    }
    .card:hover {
        transform: scale(1.05);
    }
    .card {
        box-shadow: rgba(0, 0, 0, 0.19) 0px 10px 20px, rgba(0, 0, 0, 0.23) 0px 6px 6px; 
        border-radius: 0;
        max-width: 100%; 
        min-width: 250px;
        cursor:pointer;
        min-height:125px;
    }
</style>
{% endblock css %}

{% block content %}

<div class="row">
	<div class="col">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item active">Início</li>
			</ol>
		</nav>
	</div>
</div> <!-- breadcrumb -->


<div class="row">
    <div class="col-lg-3 col-sm-6 col-12 text-center d-sm-flex justify-content-center">
        <div class="card text-white bg-primary mb-3">
            <div class="card-body d-flex align-items-center justify-content-center">
                <h3 class="card-title text-uppercase">esctop</h3>
                <a href="{% url 'cliente_cnpj:esctop_dashboard' %}" class="stretched-link"></a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-3 col-sm-6 col-12 text-center d-sm-flex justify-content-center">
        <div class="card text-white bg-primary mb-3">
            <div class="card-body d-flex align-items-center justify-content-center">
                <h3 class="card-title text-uppercase">credcoop</h3>
                <a href="{% url 'cliente:credcoop_dashboard' %}" class="stretched-link"></a>
            </div>
        </div>
    </div>
</div>

{% comment %} <div class="col-lg-3 col-sm-6 col-12 text-center d-sm-flex justify-content-center">
    <div class="card border-success mb-3" style="max-width: 100%; min-width: 250px; box-shadow: rgba(0, 0, 0, 0.19) 0px 10px 20px, rgba(0, 0, 0, 0.23) 0px 6px 6px;">
        <div class="card-header card text-center">
            <i class="fa-solid fa-calendar text-success"> Aniversariantes</i>
        </div>
        <div class="card-body text-success">
            {% if total_aniversariantes > 0 %}
                <p class="badge badge-primary">{{total_aniversariantes}} Aniversariante{% if total_aniversariantes != 1 %}(s){% endif %}</p>
                <a href="{% url 'core:aniversariantes'%}" class="btn btn-success btn-block">Ver lista</a>
            {% else %}
                <p class="badge badge-primary">Nenhum aniversariante hoje</p>
            {% endif %}
        </div>
    </div>
</div> {% endcomment %}

{% endblock content %}