projeto/avalista/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from projeto.avalista import views as v

app_name='avalista' 

urlpatterns = [
    path('delete-avalista-esctop/<int:pk>/', login_required(v.EsctopAvalistaDelete.as_view()), name='esctop_avalista_delete'),
    path('detalhes-avalista-esctop/<int:pk>/', login_required(v.EsctopAvalistaDetail.as_view()), name='esctop_avalista_detail'),
    path('formulario-fiador-esctop/', login_required(v.EsctopAvalistaCreate.as_view()), name='esctop_avalista_create'),
    path('atualiza-avalista-esctop/<int:pk>/', login_required(v.EsctopFiadorUpdate.as_view()), name='esctop_avalista_update'),
    path('avalistas-esctop/', login_required(v.EsctopAvalistaList.as_view()), name='esctop_avalista_list'),
]

projeto/cliente_cnpj/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from projeto.cliente_cnpj import views as v

app_name='cliente_cnpj'

urlpatterns = [
    path('esctop-escolha/', login_required(v.EsctopClienteDecision.as_view()), name='esctop_cliente_decision'),
    path('esctop-delete/<int:pk>/', login_required(v.EsctopClienteDelete.as_view()), name='esctop_delete'),
    path('detalhes-cliente-esctop/<int:pk>/', login_required(v.EsctopClienteDetail.as_view()), name='esctop_cliente_detail'),
    path('formulario-cliente-esctop/', login_required(v.EsctopClienteCreate.as_view()), name='esctop_cliente_create'),
    path('atualiza-cliente-esctop/<int:pk>/', login_required(v.EsctopClienteUpdate.as_view()), name='esctop_cliente_update'),
    path('clientes-esctop/', login_required(v.EsctopClientList.as_view()), name='esctop_cliente_list'),
    
    # APIS
    path('esctop-api/clientes/', login_required(v.EsctopClienteCreateAPI.as_view()), name='esctop_cliente_create_api'),
]

projeto/core/urls.py
from django.urls import path
from projeto.core import views as v
from projeto.core.views import SignUpView


app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('aniversariantes_lista/', v.aniversariantes, name='aniversariantes'),
    path('cliente_select/', v.cliente_select, name='cliente_select'),
    path('fiador_decision/', v.fiador_decision, name='fiador_decision'),
    path('fiador_decision_1/', v.fiador_decision_1, name='fiador_decision_1'),
    path('registro/', SignUpView.as_view(), name='register'),
]

projeto/emprestimo/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from projeto.emprestimo import views as v

app_name='emprestimo' 

urlpatterns = [

    # Credcoop
    path('formulario-emprestimo-credcoop/', login_required(v.CredcoopEmprestimoCreate.as_view()), name='credcoop_emprestimo_form'),
    path('emprestimos-credcoop/', login_required(v.CredcoopEmprestimoList.as_view()), name='credcoop_emprestimo_list'),

    # Credcoop Impressos
    path('<int:pk>/credcoop_promissoria/', login_required(v.CredcoopPromissoria.as_view()), name='credcoop_promissoria'),
    path('<int:pk>/credcoop_contrato/', login_required(v.CredcoopContrato.as_view()), name='credcoop_contrato'),
    path('<int:pk>/credcoop_contrato_e_promissoria/', login_required(v.CredcoopContratoPromissoria.as_view()), name='credcoop_contrato_e_promissoria'),

    # Esctop
    path('formulario-emprestimo-esctop/', login_required(v.EsctopEmprestimoCreate.as_view()), name='esctop_emprestimo_form'),
    path('emprestimos-esctop/', login_required(v.EsctopEmprestimoList.as_view()), name='esctop_emprestimo_list'),    
    
    # Esctop impressos
    path('<int:pk>/esctop_promissoria/', login_required(v.EsctopPromissoria.as_view()), name='esctop_promissoria'),
    path('<int:pk>/esctop_contrato/', login_required(v.EsctopContrato.as_view()), name='esctop_contrato'),
    path('<int:pk>/esctop_contrato_e_promissoria/', login_required(v.EsctopContratoPromissoria.as_view()), name='esctop_contrato_e_promissoria'),


    path('emprestimo-delete/<int:pk>/', login_required(v.EmprestimoDelete.as_view()), name='emprestimo_delete'),
    path('detalhes-emprestimo/<int:pk>/', login_required(v.EmprestimoDetail.as_view()), name='emprestimo_detail'),

    path('<int:pk>/pagamento_add/', v.emprestimo_pagamento_add, name='emprestimo_pagamento_add'),
    path('<int:pk>/pagamento/', v.emprestimo_pagamento, name='emprestimo_pagamento'),
    path('<int:pk>/pagamento_list/', v.emprestimo_pagamento_list, name='emprestimo_pagamento_list'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    # project
    path('api/', include('projeto.public.urls')),
    path('accounts/', include('projeto.accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('emprestimo/', include('projeto.emprestimo.urls')),   
    path('estoque/', include('projeto.estoque.urls')),
    path('credcoop/', include('projeto.cliente.urls')),
    path('esctop/', include('projeto.cliente_cnpj.urls')),
    path('avalista/', include('projeto.avalista.urls')),
    path('accounts-user/', include('django.contrib.auth.urls')),
    
    # Files
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
    # API
    path('api/auth/', include('rest_framework.urls'))
]

projeto/cliente_cnpj/models.py
from django.db import models
from django.urls import reverse_lazy
from projeto.cliente.models import Cliente
from projeto.avalista.models import Avalista
from projeto.core.models import Banco, Chave_PIX, Tipo_de_conta


class Cliente_cnpj(models.Model):
    razao_social          = models.CharField("Razão Social", max_length=50, blank=False, null=True)
    nome_fantasia         = models.CharField("Nome Fantasia", max_length=50, blank=True, null=True)
    cnpj                  = models.CharField("CNPJ", max_length=36, unique=True, blank=True, null=True)
    fundacao              = models.DateField("Fundação",max_length=8, blank=True, null=True)      
    inscricao_estadual    = models.CharField("Inscrição Estadual",blank=True, null=True, max_length=50)
    inscricao_municipal   = models.CharField("Inscrição Municipal", blank=True, null=True,max_length=50)
    #ENDEREÇO
    cep                   = models.CharField("CEP", max_length=10, blank=False, null=True)
    rua                   = models.CharField("Rua", max_length=60, blank=False, null=True)
    bairro                = models.CharField("Bairro", max_length=40, blank=False, null=True)
    cidade                = models.CharField("Cidade", max_length=40, blank=False, null=True)
    uf                    = models.CharField("UF", max_length=2, blank=False, null=True)   
    numero_casa           = models.CharField("Nº ", max_length=5, blank=True, null=True)
    ponto_referencia      = models.CharField("Ponto de Referencia", max_length=100, blank=True, null=True)
    complemento           = models.CharField("Complemento", max_length=100, blank=True, null=True)
    #CONTATO
    contato1              = models.CharField("Contato 1",max_length=15, blank=True, null=True)
    contato2              = models.CharField("Contato 2",max_length=15, blank=True, null=True)
    celular1              = models.CharField("Celular 1",max_length=17, blank=True, null=True)
    whatsapp1             = models.BooleanField("Whatsapp", default=True)
    celular2              = models.CharField("Celular 2",max_length=17, blank=True, null=True)
    whatsapp2             = models.BooleanField("Whatsapp", default=True)
    email                 = models.EmailField("Email", max_length=50, blank=True, null=True)
    # DADOS BANCÁRIOS
    banco                 = models.ForeignKey(Banco, on_delete=models.PROTECT,max_length=25, blank=True, null=True)  
    n_operacao            = models.CharField("Nº operação",max_length=15, blank=True, null=True)
    tipo_de_conta         = models.ForeignKey(Tipo_de_conta, on_delete=models.PROTECT,max_length=25, blank=True, null=True)  
    agencia               = models.CharField("Nº agência",max_length=15, blank=True, null=True)
    conta                 = models.CharField("Nº conta",max_length=15, blank=True, null=True)    
    tipo_de_chave_pix     = models.ForeignKey(Chave_PIX, on_delete=models.PROTECT,max_length=50, blank=True, null=True)
    chave_pix             = models.CharField("Chave Pix", max_length=255, blank=True, null=True)
    
    # REFERÊNCIAS
    ref1_nome             = models.CharField("Nome", max_length=50, blank=True, null=True)
    ref1_contato          = models.CharField("Contato",max_length=17, blank=True, null=True)
    ref1_parentesco       = models.CharField("Parentesco", max_length=50, blank=True, null=True)
    ref2_nome             = models.CharField("Nome", max_length=50, blank=True, null=True)
    ref2_contato          = models.CharField("Contato",max_length=17, blank=True, null=True)
    ref2_parentesco       = models.CharField("Parentesco", max_length=50, blank=True, null=True)
    #REPRESENTANTE
    rep_nome              = models.CharField("Nome", max_length=50, blank=True, null=True)
    rep_cpf               = models.CharField("CPF", max_length=20, unique=True, blank=True, null=True) 
    rep_rg                = models.CharField("RG",max_length=20, blank=True, null=True)
    rep_orgao_emissor     = models.CharField("Orgão Emissor",max_length=20, blank=True, null=True)
    rep_pai               = models.CharField("Nome do Pai",max_length=50, blank=True, null=True)
    rep_mae               = models.CharField("Nome da Mãe",max_length=50, blank=True, null=True)
    rep_data_nasc         = models.DateField("Data de Nascimento",max_length=8, blank=True, null=True)
    rep_naturalidade      = models.CharField("Naturalidade", max_length=20, blank=True, null=True)
    rep_nacionalidade     = models.CharField("Nacionalidade",max_length=20, blank=True, null=True)
    rep_estado_civil      = models.CharField("Estado Civil",max_length=20, blank=True, null=True)
    rep_conjuge_nome      = models.CharField("Nome Cônjuge", max_length=50, blank=True, null=True)
    rep_conjuge_cpf       = models.CharField("CPF Cônjuge", max_length=20, unique=True,blank=True, null=True)
    rep_conjuge_telefone  = models.CharField("Contato Cônjuge",max_length=17, blank=True, null=True)
    #REPRESENTANTE CONTATO
    rep_contato1          = models.CharField("Tel Fixo",max_length=15, blank=True, null=True)
    rep_celular1          = models.CharField("Celular 1",max_length=17, blank=True, null=True)
    rep_whatsapp1         = models.BooleanField("Whatsapp", default=True)
    rep_celular2          = models.CharField("Celular 2",max_length=17, blank=True, null=True)
    rep_whatsapp2         = models.BooleanField("Whatsapp", default=True)
    rep_email             = models.EmailField("Email", max_length=50, blank=True, null=True)
    #REPRESENTANTE EMAIL
    rep_cep               = models.CharField("CEP", max_length=10, blank=True, null=True)
    rep_rua               = models.CharField("Rua", max_length=60, blank=True, null=True)
    rep_bairro            = models.CharField("Bairro", max_length=40, blank=True, null=True)
    rep_cidade            = models.CharField("Cidade", max_length=40, blank=True, null=True)
    rep_uf                = models.CharField("UF", max_length=2, blank=True, null=True)   
    rep_numero_casa       = models.CharField("Nº ", max_length=5, blank=True, null=True)
    rep_ponto_referencia  = models.CharField("Ponto de Referencia", max_length=100, blank=True, null=True)  
    #REPRESENTANTE FIADOR
    fiador                = models.ForeignKey(Avalista, on_delete=models.PROTECT, blank=True, null=True)
    fiador_inativo        = models.BooleanField("Fiador inativo", default=False)

    class Meta:
        ordering = ('razao_social',)
        
    def __str__(self):
        return self.razao_social if self.razao_social else "Sem razão social cadastrado"
    
    def get_absolute_url(self):
        return reverse_lazy('cliente_cnpj:esctop_cliente_detail', kwargs={'pk': self.pk})

    # def save(self, force_insert=False, force_update=False):
    #     self.razao_social = self.razao_social.upper()
    #     super(Cliente_cnpj, self).save(force_insert, force_update)


# CRIAR UM TEMPLATE PRA RECEBER ESTES DOIS JÁ SALVOS

projeto/cliente_cnpj/forms.py
from django import forms
from .models import Cliente_cnpj


class Cliente_cnpjForm(forms.ModelForm):
    class Meta:
        model = Cliente_cnpj
        fields = '__all__'
        widgets = {
            'ref1_nome': forms.TextInput(attrs={'placeholder': 'Refencia 1'}),
            'ref2_nome': forms.TextInput(attrs={'placeholder': 'Refencia 2'}),            
            'complemento': forms.TextInput(attrs={'placeholder': 'Ex: Apt A, BL B'}),   
            'rep_conjuge_nome': forms.TextInput(attrs={'placeholder': 'Opcional'}), 
            'rep_conjuge_cpf': forms.TextInput(attrs={'placeholder': 'Opcional'}), 
            'rep_conjuge_telefone': forms.TextInput(attrs={'placeholder': 'Opcional'}),          
        }

projeto/cliente_cnpj/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from .models import Cliente_cnpj
from projeto.avalista.models import Avalista
from .forms import Cliente_cnpjForm
from projeto.avalista.forms import AvalistaForm
from django.db.models.query_utils import Q
from rest_framework import generics
from .serializers import Cliente_cnpjSerializer
from rest_framework.renderers import JSONRenderer



class EsctopClienteDecision(CreateView):
    model=Cliente_cnpj
    template_name='esctop_cliente_decision.html'
    form_class=Cliente_cnpjForm


class EsctopClienteDelete(DeleteView):
    model=Cliente_cnpj
    template_name ='esctop_cliente_delete.html'
    success_url = reverse_lazy('cliente_cnpj:esctop_cliente_list')


class EsctopClienteDetail(DetailView):
    model=Cliente_cnpj
    template_name='esctop_cliente_detail.html'
    form_class=Cliente_cnpjForm


class EsctopClienteCreate(CreateView):
    model=Cliente_cnpj
    template_name='esctop_cliente_form.html'
    form_class=Cliente_cnpjForm
    


class EsctopClienteCreateAPI(generics.CreateAPIView):
    serializer_class = Cliente_cnpjSerializer
    # renderer_classes = [JSONRenderer]

class EsctopClienteUpdate(UpdateView):
    model=Cliente_cnpj
    template_name='esctop_cliente_form.html'
    form_class = Cliente_cnpjForm


class EsctopClientList(ListView):
    model=Cliente_cnpj
    template_name='esctop_cliente_list.html'
    paginate_by = 20
    context_object_name = "objects"

    def get_queryset(self):
        queryset=super().get_queryset()

        if self.request.GET.get('search_by'):
            queryset = queryset.filter(
                Q(
                    Q(razao_social__icontains=self.request.GET.get('search_by'))|
                    Q(nome_fantasia__icontains=self.request.GET.get('search_by'))|
                    Q(rep_nome__icontains=self.request.GET.get('search_by'))|
                    Q(cnpj__icontains=self.request.GET.get('search_by'))
                )
            )

        return queryset
    
    def get_context_data(self, **kwargs):
        context = super(EsctopClientList, self).get_context_data(**kwargs)
        context['params'] = self.request.META['QUERY_STRING']		
        context['search_by'] = self.request.GET.get('search_by')
        context['page_title'] = "Clientes Esctop"

        return context











# ***********************NÃO APAGAR ESTA VIEW COMENTADA ABAIXO************************
# @login_required
# def cliente_cnpjupdate(request, pk):
#     data = {}
#     cliente_cnpj = Cliente_cnpj.objects.get(pk=pk)
#     form = Cliente_cnpjForm(request.POST or None, instance=cliente_cnpj)
#     data['cliente_cnpj'] = cliente_cnpj
#     data['form'] = form

#     if request.method == 'POST':
#         if form.is_valid():
#             form.save()
#             return redirect('cliente_cnpj:cliente_cnpj_list')
#         else:
#             # messages.error(request, 'Dados inválidos')
#             return render(request, 'cliente_cnpj_form.html', data)  
#     else:
#         return render(request, 'cliente_cnpj_form.html', data) 

projeto/cliente_cnpj/templates/cliente_cnpj_delete.html
{% extends 'base.html' %}

{% block content %}

<h2>Tem certeza que quer deletar: {{ object }}</h2>

<div class="row">   
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Sim">
            <a href="{% url 'cliente_cnpj:esctop_cliente_list' %}" class="btn btn-primary">Não</a>
        </form>
    </div>
</div>

{% endblock content %}

projeto/cliente_cnpj/templates/esctop_dashboard.html
{% extends 'base.html' %}

{% block css %}

<style>
    i {
        font-size: 1.5em;
    }

    .card {
        min-height: 125px;
    }

    .card:hover {
        transform: scale(1.05);
    }

    .card {
        box-shadow: rgba(0, 0, 0, 0.19) 0px 10px 20px, rgba(0, 0, 0, 0.23) 0px 6px 6px;
        border-radius: 0;
        max-width: 100%;
        min-width: 250px;
        cursor: pointer;
        min-height: 130px;
    }

    .dash-label {
        color: #000000 !important;
        background-image: linear-gradient(15deg, #cdd5dd 50%, #5eaa84 600%);
    }
</style>
{% endblock css %}

{% block content %}

<div class="row">
    <div class="col">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Início</a></li>
                <li class="breadcrumb-item active" aria-current="page">Dashboard Esctop</li>
            </ol>
        </nav>
    </div>
</div> <!-- breadcrumb -->

<div class="container-fluid">
    <div class="row border border-danger">
        <div class="col-md-6 border border-success">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Seção 1</h5>
                    <p class="card-text">Conteúdo da seção 1.</p>
                </div>
            </div>
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">Seção 2</h5>
                    <p class="card-text">Conteúdo da seção 2.</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Seção 3</h5>
                    <p class="card-text">Conteúdo da seção 3.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<h5 class="label">Cliente</h5>
<div class="row">
    <div class="col-lg-3 col-sm-6 col-12">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                Título do Card
            </div>
            <div class="card-body">
                <h5 class="card-title">Subtítulo do Card</h5>
                <p class="card-text">Conteúdo do Card</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Informação 1
                    <span class="badge badge-primary badge-pill">5</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Informação 2
                    <span class="badge badge-secondary badge-pill">2</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Informação 3
                    <span class="badge badge-success badge-pill">1</span>
                </li>
            </ul>
            <div class="card-footer text-muted">
                Última atualização 3 mins atrás
            </div>
        </div>

    </div>
    <div class="col-lg-3 col-sm-6 col-12">
        <div class="card" style="width: 18rem;">
            <img src="imagem.png" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Título do Card</h5>
                <p class="card-text">Conteúdo do Card</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Informação 1</li>
                <li class="list-group-item">Informação 2</li>
                <li class="list-group-item">Informação 3</li>
            </ul>
            <div class="card-footer text-muted">
                Última atualização 3 mins atrás
            </div>
        </div>

    </div>
    <div class="col-lg-3 col-sm-6 col-12">
        <div class="card">
            <img src="imagem.png" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-danger">Título do Card</h5>
                <p class="card-text">Conteúdo do Card</p>
            </div>
            <div class="card-footer bg-light">
                Rodapé do Card
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6 col-12">
        <div class="card bg-dark text-white">
            <div class="card-header bg-primary">
                Título do Card
            </div>
            <div class="card-body">
                <p class="card-text">Conteúdo do Card</p>
            </div>
            <div class="card-footer bg-secondary">
                Rodapé do Card
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6 col-12">
        <div class="card bg-dark text-white">
            <div class="card-header bg-primary">
                Título do Card
            </div>
            <div class="card-body">
                <p class="card-text">Conteúdo do Card</p>
            </div>
            <div class="card-footer bg-secondary">
                Rodapé do Card
            </div>
        </div>
    </div>

    <div class="col-lg-3 col-sm-6 col-12">
        <div class="card bg-light">
            <div class="card-header bg-info text-white">
                Título do Card
            </div>
            <div class="card-body">
                <p class="card-text">Conteúdo do Card</p>
            </div>
            <div class="card-footer bg-warning">
                Rodapé do Card
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6 col-12">

        <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
                <div class="col-md-4 bg-primary">
                    <img src="imagem.png" class="card-img" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title text-success">Título do Card</h5>
                        <p class="card-text">Conteúdo do Card</p>
                        <p class="card-text"><small class="text-muted">Última atualização 3 mins atrás</small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6 col-12">
        <div class="card bg-success text-white my-2">
            <div class="card-body">
                <h5 class="card-title">
                    {% comment %} <i class="fa-solid fa-plus"></i> {% endcomment %}
                    Cadastro de Cliente</h5>
                <p class="card-text"></p>
            </div>
            <a href="{% url 'cliente_cnpj:esctop_cliente_create' %}" class="stretched-link"></a>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6 col-12">
        <div class="card bg-success text-white my-2">
            <div class="card-body">
                <h5 class="card-title">
                    {% comment %} <i class="fa-solid fa-plus"></i> {% endcomment %}
                    Cadastro de Fiador</h5>
                <p class="card-text"></p>
            </div>
            <a href="{% url 'avalista:esctop_avalista_create' %}" class="stretched-link"></a>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6 col-12">
        <div class="card bg-success text-white my-2">
            <div class="card-body">
                <h5 class="card-title">
                    {% comment %} <i class="fa-solid fa-list"></i> {% endcomment %}
                    Lista de Clientes
                </h5>
                <p class="card-text">Total: {{total_clients_esctop}}</p>
            </div>
            <a href="{% url 'cliente_cnpj:esctop_cliente_list' %}" class="stretched-link"></a>
        </div>
    </div>
</div> <!-- row -->


<h5 class="label pt-4">Empréstimo</h5>

<div class="row">
    <div class="col-lg-3 col-sm-6 col-12">
        <div class="card bg-primary text-white my-2">
            <div class="card-body">
                <h5 class="card-title">
                    {% comment %} <i class="fa-solid fa-plus"></i> {% endcomment %}
                    Cadastrar um Empréstimos
                </h5>
                <p class="card-text">Total: {{total_loans_esctop}}</p>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6 col-12">
        <div class="card bg-primary text-white my-2">
            <div class="card-body">
                <h5 class="card-title">
                    {% comment %} <i class="fa-solid fa-list"></i> {% endcomment %}
                    Lista de Empréstimos
                </h5>
                <p class="card-text">Total: {{total_loans_esctop}}</p>
            </div>
        </div>
    </div>
</div> <!-- row -->














{% comment %} <div class="row">
    <div class="col-lg-3 col-sm-6 col-12 text-center d-sm-flex justify-content-center">
        <div class="card text-white bg-primary mb-3"
            style="max-width: 100%; min-width: 250px; box-shadow: rgba(0, 0, 0, 0.19) 0px 10px 20px, rgba(0, 0, 0, 0.23) 0px 6px 6px; border-radius: 0;">
            <div class="card-body d-flex align-items-center justify-content-center">
                <h3 class="card-title text-uppercase">Empréstimos</h3>
                <a href="{% url 'emprestimo:esctop_emprestimo_list' %}" class="stretched-link"></a>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-sm-6 col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Empréstimos</h5>
                <div class="row">
                    <div class="col-6">
                        <p class="card-text">Total</p>
                        <h3 class="card-title">1.234</h3>
                    </div>
                    <div class="col-6">
                        <p class="card-text">Receita total:</p>
                        <h3 class="card-title">$10.000</h3>
                    </div>
                    <div class="col-6">
                        <p class="card-text">Pedidos pendentes:</p>
                        <h3 class="card-title">23</h3>
                    </div>
                    <div class="col-6">
                        <p class="card-text">Tempo médio de resposta:</p>
                        <h3 class="card-title">2h 15min</h3>
                    </div>
                </div>
            </div>
        </div>

    </div><!-- col -->

</div> {% endcomment %}

{% comment %} <section class="mt-4">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Empréstimo</h2>
                <p class="lead">Veja abaixo as informações do seu empréstimo:</p>
                <ul class="list-group">
                    <li class="list-group-item bg-primary text-white">
                        <span class="font-weight-bold">Valor solicitado:</span>
                        <span class="float-right">$10.000</span>
                    </li>
                    <li class="list-group-item bg-success text-white">
                        <span class="font-weight-bold">Taxa de juros:</span>
                        <span class="float-right">12% ao ano</span>
                    </li>
                    <li class="list-group-item bg-info text-white">
                        <span class="font-weight-bold">Prazo:</span>
                        <span class="float-right">36 meses</span>
                    </li>
                    <li class="list-group-item bg-warning text-white">
                        <span class="font-weight-bold">Valor das parcelas:</span>
                        <span class="float-right">$350,00</span>
                    </li>
                    <li class="list-group-item bg-danger text-white">
                        <span class="font-weight-bold">Data do primeiro pagamento:</span>
                        <span class="float-right">10/03/2023</span>
                    </li>
                </ul>
            </div>
            <div class="col-md-6">
                <img src="https://via.placeholder.com/500x300" class="img-fluid rounded">
            </div>
        </div>
    </div>
</section> {% endcomment %}






{% endblock content %}