projeto/cliente/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from projeto.cliente import views as v

app_name='cliente' 

urlpatterns = [
    path('credcoop-escolha/', login_required(v.CredcoopClienteDecision.as_view()), name='credcoop_decision'),
    path('credcoop-delete/<int:pk>/', login_required(v.CredcoopClienteDelete.as_view()), name='credcoop_cliente_delete'),
    path('detalhes-cliente-credcoop/<int:pk>/', login_required(v.CredcoopClienteDetail.as_view()), name='credcoop_client_detail'),
    path('formulario-cliente-credcoop/', login_required(v.CredcoopClienteCreate.as_view()), name='credcoop_cliente_create'),
    path('atualiza-cliente-credcoop/<int:pk>/', login_required(v.CredcoopClienteUpdate.as_view()), name='credcoop_update'),
    path('clientes-credcoop/', login_required(v.CredcoopClienteList.as_view()), name='credcoop_cliente_list'),
    path('dashboard-credcoop/', login_required(v.CredcoopDashboard.as_view()), name='credcoop_dashboard'),

    # Fiador
    path('formulario-fiador-credcoop/', login_required(v.CredcoopFiadorCreate.as_view()), name='credcoop_fiador_create'),
]

projeto/core/urls.py
from django.urls import path
from projeto.core import views as v
from projeto.core.views import SignUpView


app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('aniversariantes_lista/', v.aniversariantes, name='aniversariantes'),
    path('cliente_select/', v.cliente_select, name='cliente_select'),
    path('fiador_decision/', v.fiador_decision, name='fiador_decision'),
    path('fiador_decision_1/', v.fiador_decision_1, name='fiador_decision_1'),
    path('registro/', SignUpView.as_view(), name='register'),
]

projeto/credcoop/urls.py
from projeto.credcoop.api.credcoopapi import ClienteCredcoopListAPIView
from django.urls import path

app_name='credcoop' 

urlpatterns = [
    
    path('api/credcoop', ClienteCredcoopListAPIView.as_view(), name='api_credcoop'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    # project
    path('api/', include('projeto.public.urls')),
    path('accounts/', include('projeto.accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('emprestimo/', include('projeto.emprestimo.urls')),   
    path('estoque/', include('projeto.estoque.urls')),
    path('credcoop/', include('projeto.cliente.urls')),
    path('esctop/', include('projeto.cliente_cnpj.urls')),
    path('avalista/', include('projeto.avalista.urls')),
    path('accounts-user/', include('django.contrib.auth.urls')),
    
    # Files
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
    # API
    path('api/auth/', include('rest_framework.urls'))
]

projeto/cliente/models.py
#para campo required
#https://stackoverflow.com/questions/1134667/django-required-field-in-model-form/1429646
from django.db import models
from django.urls import reverse_lazy
from projeto.core.models import Banco, Chave_PIX, Tipo_de_conta


class Cliente(models.Model):
    #Dados pessoais do Cliente Credcoop
    nome                  = models.CharField("Nome", max_length=50, blank=False, null=True)
    cpf                   = models.CharField("CPF", max_length=20, unique=True)
    rg                    = models.CharField("RG",max_length=20, blank=False, null=True)
    orgao_emissor         = models.CharField("Orgão Emissor", max_length=15, blank=False, null=True)
    data_nasc             = models.DateField("Data de Nascimento",max_length=8, blank=False, null=True)
    naturalidade          = models.CharField("Naturalidade", max_length=20, blank=False, null=True)    
    nacionalidade         = models.CharField("Nacionalidade", max_length=15, blank=True, null=True)
    estado_civil          = models.CharField("Estado Civil", max_length=15, blank=True, null=True)  
    conjuge_nome          = models.CharField("Nome Cônjuge", max_length=50, blank=True, null=True)
    conjuge_cpf           = models.CharField("CPF Cônjuge", max_length=20, unique=True,blank=True, null=True)
    conjuge_telefone      = models.CharField("Contato Cônjuge",max_length=17, blank=True, null=True)
    nome_da_mae           = models.CharField("Nome da Mãe", max_length=50, blank=False, null=True)
    nome_do_pai           = models.CharField("Nome da Pai", max_length=50, blank=True, null=True)
    # ENDEREÇO
    cep                   = models.CharField("CEP", max_length=10, blank=False, null=True)
    rua                   = models.CharField("Rua", max_length=60, blank=False, null=True)
    bairro                = models.CharField("Bairro", max_length=40, blank=False, null=True)
    cidade                = models.CharField("Cidade", max_length=40, blank=False, null=True)
    uf                    = models.CharField("UF", max_length=2, blank=False, null=True)   
    numero_casa           = models.CharField("Nº ", max_length=5, blank=True, null=True)
    ponto_referencia      = models.CharField("Ponto de Referencia", max_length=100, blank=True, null=True)
    complemento           = models.CharField("Complemento", max_length=100, blank=True, null=True)
    # CONTATO
    contato1              = models.CharField("Contato 1",max_length=15, blank=True, null=True)
    contato2              = models.CharField("Contato 2",max_length=15, blank=True, null=True)
    celular1              = models.CharField("celular 1",max_length=17, blank=True, null=True)
    celular2              = models.CharField("celular 2",max_length=17, blank=True, null=True)
    whatsapp1             = models.BooleanField("Whatsapp", default=False)
    whatsapp2             = models.BooleanField("Whatsapp", default=False)
    email                 = models.EmailField("Email", max_length=50, blank=True, null=True)    
    # ONDE VAI ESSE CAMPO?
    sacado                = models.CharField("Sacado",max_length=50, blank=True, null=True)
    # DADOS DO LOCAL DE TRABALHO
    nome_fantasia         = models.CharField("Nome Fantasia",max_length=50, blank=True, null=True)
    contato1_trabalho     = models.CharField("Contato 1",max_length=15, blank=True, null=True)
    contato2_trabalho     = models.CharField("Contato 2",max_length=15, blank=True, null=True)
    celular1_trabalho     = models.CharField("celular 1",max_length=17, blank=True, null=True)
    celular2_trabalho     = models.CharField("celular 2",max_length=17, blank=True, null=True)
    whatsapp1_trabalho    = models.BooleanField("Whatsapp", default=False)
    whatsapp2_trabalho    = models.BooleanField("Whatsapp", default=False)
    cep_trabalho          = models.CharField("CEP", max_length=10, blank=True, null=True)
    rua_trabalho          = models.CharField("Rua", max_length=60, blank=True, null=True)
    bairro_trabalho       = models.CharField("Bairro", max_length=40, blank=True, null=True)
    cidade_trabalho       = models.CharField("Cidade", max_length=40, blank=True, null=True)
    uf_trabalho           = models.CharField("Estado", max_length=2, blank=True, null=True)
    numero_casa_trabalho  = models.CharField("Nº ", max_length=5, blank=True, null=True)
    referencia_trabalho   = models.CharField("Ponto de Referencia",max_length=50, blank=True, null=True)  
    obs_trabalho          = models.TextField("Observações",max_length=200, blank=True, null=True)
    # DADOS BANCÁRIOS
    banco                 = models.ForeignKey(Banco, on_delete=models.PROTECT,max_length=25, blank=True, null=True)  
    n_operacao            = models.CharField("Nº operação",max_length=15, blank=True, null=True)
    agencia               = models.CharField("Nº agência",max_length=15, blank=True, null=True)
    conta                 = models.CharField("Nº conta",max_length=15, blank=True, null=True)   
    tipo_de_conta         = models.ForeignKey(Tipo_de_conta, on_delete=models.PROTECT,max_length=25, blank=True, null=True)
    tipo_de_chave_pix     = models.ForeignKey(Chave_PIX, on_delete=models.PROTECT,max_length=50, blank=True, null=True)
    chave_pix             = models.CharField("Chave Pix", max_length=255, blank=True, null=True)   

    # REFERÊNCIAS
    ref1_nome             = models.CharField("Nome", max_length=50, blank=True, null=True)
    ref1_contato          = models.CharField("Contato",max_length=17, blank=True, null=True)
    ref1_parentesco       = models.CharField("Parentesco", max_length=50, blank=True, null=True)
    ref2_nome             = models.CharField("Nome", max_length=50, blank=True, null=True)
    ref2_contato          = models.CharField("Contato",max_length=17, blank=True, null=True)
    ref2_parentesco       = models.CharField("Parentesco", max_length=50, blank=True, null=True)
    ref3_nome             = models.CharField("Nome", max_length=50, blank=True, null=True)
    ref3_contato          = models.CharField("Contato",max_length=17, blank=True, null=True)
    ref3_parentesco       = models.CharField("Parentesco", max_length=50, blank=True, null=True)

    fiador                = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    fiador_inativo        = models.BooleanField("Fiador inativo", default=False)


    class Meta:
        ordering = ('nome',) #confirme se é a organização e apague o coment

    def __str__(self):
        return self.nome if self.nome else "sem cliente credcoop"
    
    def get_absolute_url(self):
        return reverse_lazy('cliente:credcoop_client_detail', kwargs={'pk': self.pk})
    
    def save(self, force_insert=False, force_update=False):
        self.nome = self.nome.upper()
        super(Cliente, self).save(force_insert, force_update)

projeto/cliente/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):    
    class Meta:
        model = Cliente
        fields = '__all__'
        widgets = {
            'complemento': forms.TextInput(attrs={'placeholder': 'Ex: Apt A, BL B'}),             
            'ref1_nome': forms.TextInput(attrs={'placeholder': 'Refencia 1'}),
            'ref2_nome': forms.TextInput(attrs={'placeholder': 'Refencia 2'}),            
            'ref3_nome': forms.TextInput(attrs={'placeholder': 'Refencia 3'}),            
            'complemento': forms.TextInput(attrs={'placeholder': 'Ex: Apt A, BL B'}), 
            'conjuge_nome': forms.TextInput(attrs={'placeholder': 'Opcional'}), 
            'conjuge_cpf': forms.TextInput(attrs={'placeholder': 'Opcional'}), 
            'conjuge_telefone': forms.TextInput(attrs={'placeholder': 'Opcional'}), 
        }
    # def existe_cpf(self):
    #     cpf = self.cleaned_data['cpf']
    #     if Cliente.objects.filter(cpf=cpf).exists():
    #         print("CPF já existe")
    #         raise forms.ValidationError('CPF ja cadastrado!')
    #     return cpf   
        

projeto/cliente/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView, TemplateView
from django.core.paginator import Paginator
from .models import Cliente
from .forms import ClienteForm

from django.db.models.query_utils import Q


# Views do Cliente Credcoop
class CredcoopClienteDecision(CreateView):
    model=Cliente
    template_name='credcoop_cliente_decision.html'
    form_class=ClienteForm


class CredcoopClienteDelete(DeleteView):
    model=Cliente
    template_name ='credcoop_cliente_delete.html'    
    success_url = reverse_lazy('cliente:credcoop_cliente_list')


class CredcoopClienteDetail(DetailView):
    model=Cliente
    template_name='credcoop_cliente_detail.html'
    form_class=ClienteForm


class CredcoopClienteCreate(CreateView):
    model=Cliente
    template_name='credcoop_cliente_form.html'
    form_class=ClienteForm


class CredcoopClienteUpdate(UpdateView):
    model=Cliente
    template_name='credcoop_cliente_form.html'
    form_class = ClienteForm
    #fazer aqui receber o form dos emprestimos filtrados apenas dele


class CredcoopClienteList(ListView):
    model=Cliente
    template_name='credcoop_cliente_list.html'
    paginate_by = 20
    context_object_name = "objects"

    def get_queryset(self):
        queryset=super().get_queryset()

        if self.request.GET.get('search_by'):
            queryset = queryset.filter(
                Q(
                    Q(nome__icontains=self.request.GET.get('search_by'))|
                    Q(rg__icontains=self.request.GET.get('search_by'))|
                    Q(cpf__icontains=self.request.GET.get('search_by'))
                )
            )

        return queryset
    
    def get_context_data(self, **kwargs):
        context = super(CredcoopClienteList, self).get_context_data(**kwargs)
        context['params'] = self.request.META['QUERY_STRING']
		
        context['search_by'] = self.request.GET.get('search_by')

        return context


# Views do Fiador Credcoop
class CredcoopFiadorCreate(CreateView):
    model=Cliente       
    template_name='credcoop_fiador_form.html'
    form_class=ClienteForm
    success_url = reverse_lazy('cliente:credcoop_cliente_list')


class CredcoopDashboard(TemplateView):
    template_name='credcoop_dashboard.html'

    def test_func(self):
        return self.request.user.is_superuser

projeto/credcoop/views.py
from django.shortcuts import render

# Create your views here.
 

projeto/cliente/templates/cliente_delete.html
{% extends 'base.html' %}

{% block content %}

<h2>Tem certeza que quer deletar: {{ object }}</h2>

<div class="row">   
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Sim">
            <a href="{% url 'cliente:credcoop_cliente_list' %}" class="btn btn-primary">Não</a>
        </form>
    </div>
</div>

{% endblock content %}

projeto/cliente/templates/cliente_list.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock css %}

{% block content %}

<div class="row card card-body">
    <div class="col-12">
        <h2 class="text-uppercase">Lista de Clientes Credcoop</h2>
    </div>
</div>
<div class="row card card-body">
    <div class="col-12">
        <form id="formSubmit" method="get" onsubmit="setDate()">
            <div class="row">            
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="search_by">Pesquisar</label>
                        <input type="text" name="search_by" maxlength="255" class="form-control" value="{{search_by|default:''}}" placeholder="Ex: Nome do cliente, RG, CPF..." autofocus>
                    </div>
                </div>
            </div>
            <div class="row mx-0 pb-3">
                <div class="col-md-12">
                    <div class="text-right">
                        <button class="btn btn-success btn-rounded" type="submit">
                            <i class="fa-solid fa-magnifying-glass"></i>
                            <span>Filtrar</span>
                        </button>
                        <a class="btn btn-primary btn-rounded" href="{% url 'cliente:credcoop_cliente_list' %}">
                            <span >Limpar filtro</span>
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="class page-header" >
    {% if object_list %}
    
    <div class="row card card-body">
        <div class="col-12">
            <div class="table-responsive mg-t-20">
                <table class="table table-striped table-hover text-uppercase">
                    <thead class="thead btn-primary noHover">
                        <tr style="height: 25px;line-height: 25px;">
                            <th>Nome</th>                    
                            <th>RG</th>
                            <th>Data de Nascimento</th>                                        
                            <th>CPF</th>   
                            <th></th>                                
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in objects  %}
                        <tr>
                            <td>{{object.nome}}</td>                                        
                            <td>{{ object.rg }}</td>
                            <td>{{ object.data_nasc }}</td>                                     
                            <td>{{ object.cpf }}</td> 
                            <td style="text-align:center"> 
                                <a href="{{ object.get_absolute_url}}" ><button class="btn btn-info">Gerenciar</button></a> 
                            </td>                    
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% include 'includes/pagination.html' %}
    </div>
    {% else %}
        <p class="alert alert-warning">Sem Clientes cadastrados</p>
    {% endif %}

</div>

{% endblock content %}

projeto/cliente/templates/credcoop_client_list.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock css %}

{% block content %}

<div class="row card card-body">
    <div class="col-12">
        <h2 class="text-uppercase">Lista de Clientes Credcoop</h2>
    </div>
</div>
<div class="row card card-body">
    <div class="col-12">
        <form id="formSubmit" method="get" onsubmit="setDate()">
            <div class="row">            
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="search_by">Pesquisar</label>
                        <input type="text" name="search_by" maxlength="255" class="form-control" value="{{search_by|default:''}}" placeholder="Ex: Nome do cliente, RG, CPF..." autofocus>
                    </div>
                </div>
            </div>
            <div class="row mx-0 pb-3">
                <div class="col-md-12">
                    <div class="text-right">
                        <button class="btn btn-success btn-rounded" type="submit">
                            <i class="fa-solid fa-magnifying-glass"></i>
                            <span>Filtrar</span>
                        </button>
                        <a class="btn btn-primary btn-rounded" href="{% url 'cliente:credcoop_cliente_list' %}">
                            <span >Limpar filtro</span>
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="class page-header" >
    {% if object_list %}
    
    <div class="row card card-body">
        <div class="col-12">
            <div class="table-responsive mg-t-20">
                <table class="table table-striped table-hover text-uppercase">
                    <thead class="thead btn-primary noHover">
                        <tr style="height: 25px;line-height: 25px;">
                            <th>Nome</th>                    
                            <th>RG</th>
                            <th>Data de Nascimento</th>                                        
                            <th>CPF</th>   
                            <th></th>                                
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in objects  %}
                        <tr>
                            <td>{{object.nome}}</td>                                        
                            <td>{{ object.rg }}</td>
                            <td>{{ object.data_nasc }}</td>                                     
                            <td>{{ object.cpf }}</td> 
                            <td style="text-align:center"> 
                                <a href="{{ object.get_absolute_url}}" ><button class="btn btn-info">Gerenciar</button></a> 
                            </td>                    
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% include 'includes/pagination.html' %}
    </div>
    {% else %}
        <p class="alert alert-warning">Sem Clientes cadastrados</p>
    {% endif %}

</div>

{% endblock content %}

projeto/cliente/templates/credcoop_cliente_decision.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block js %}{% endblock js %}


{% block content %}

<div class="row">
	<div class="col">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="{% url 'cliente:credcoop_decision' %}">Cliente</a></li>
				<li class="breadcrumb-item active" aria-current="page">Credcoop</li>
			</ol>
		</nav>
	</div>
</div>

<h1 class="text-center mt-4 mb-4">CREDCOOP</h1>
<div class="">
    <div class="row">
        <div class="col-sm-6">
            <div class="card text-white bg-success mb-3">
                <div class="card-body">
                <h5 class="card-title">Cadastre um Cliente</h5> 
                {% comment %} <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>  {% endcomment %}
                <a href="#" class="btn btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#exampleModal">Cadastrar Cliente</a>
                </div>
            </div>
            </div>
        <div class="col-sm-6">
            <div class="card text-white bg-success mb-3">
                <div class="card-body">
                <h5 class="card-title">Cadastre um Fiador</h5>
                {% comment %} <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> {% endcomment %}
                <a href="{% url 'cliente:credcoop_fiador_create' %}" class="btn btn btn-primary btn-lg btn-block">Cadastrar Fiador</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel">O CLIENTE JÁ POSSUI FIADOR CADASTRADO?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span class="pull-center">
                        <a href="{% url 'cliente:credcoop_cliente_create' %}" type="button" class="btn btn-success">SIM</a>
                        <a href="{% url 'cliente:credcoop_fiador_create' %}" type="button" class="btn btn-danger">NÃO</a>
                    </span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>                   
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

projeto/cliente/templates/credcoop_cliente_list.html
{% extends "base.html" %}

{% block css %}
{% endblock css %}

{% block content %}

<div class="row card card-body">
    <div class="col-12">
        <h2 class="text-uppercase">Lista de Clientes Credcoop</h2>
    </div>
</div>
<div class="row card card-body">
    <div class="col-12">
        <form id="formSubmit" method="get" onsubmit="setDate()">
            <div class="row">            
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="search_by">Pesquisar</label>
                        <input type="text" name="search_by" maxlength="255" class="form-control" value="{{search_by|default:''}}" placeholder="Ex: Nome do cliente, RG, CPF..." autofocus>
                    </div>
                </div>
            </div>
            <div class="row mx-0 pb-3">
                <div class="col-md-12">
                    <div class="text-right">
                        <button class="btn btn-success btn-rounded" type="submit">
                            <i class="fa-solid fa-magnifying-glass"></i>
                            <span>Filtrar</span>
                        </button>
                        <a class="btn btn-primary btn-rounded" href="{% url 'cliente:credcoop_cliente_list' %}">
                            <span >Limpar filtro</span>
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="class page-header" >
    {% if object_list %}
    
    <div class="row card card-body">
        <div class="col-12">
            <div class="table-responsive mg-t-20">
                <table class="table table-striped table-hover text-uppercase">
                    <thead class="thead btn-primary noHover">
                        <tr style="height: 25px;line-height: 25px;">
                            <th>Nome</th>                    
                            <th>RG</th>
                            <th>Data de Nascimento</th>                                        
                            <th>CPF</th>   
                            <th></th>                                
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in objects  %}
                        <tr>
                            <td>{{object.nome}}</td>                                        
                            <td>{{ object.rg }}</td>
                            <td>{{ object.data_nasc }}</td>                                     
                            <td>{{ object.cpf }}</td> 
                            <td style="text-align:center"> 
                                <a href="{{ object.get_absolute_url}}" ><button class="btn btn-info">Gerenciar</button></a> 
                            </td>                    
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% include 'includes/pagination.html' %}
    </div>
    {% else %}
        <p class="alert alert-warning">Sem Clientes cadastrados</p>
    {% endif %}

</div>

{% endblock content %}

projeto/cliente/templates/credcoop_dashboard.html
{% extends 'base.html' %}

{% block css %}
<style>
    .card:hover {
        transform: scale(1.05);
    }
    
</style>
{% endblock css %}


{% block content %}

<div class="row">
	<div class="col">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="{% url 'core:index' %}">Início</a></li>
                <li class="breadcrumb-item active" aria-current="page">Área do Cliente Credcoop</li>
			</ol>
		</nav>
	</div>
</div>

<div class="row border border-dark p-3">
    <div class="col-lg-3 col-sm-6 col-12 text-center d-sm-flex justify-content-center" style="max-width: 100%">
        <div class="card bg-white">
            <div class="card-body">
                <h5 class="card-title text-sm-left">Empréstimos</h5>
                <a href="#" class="btn btn-primary btn-block">Cadastrar</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

projeto/cliente/templates/credcoop_decision.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block js %}{% endblock js %}


{% block content %}

<div class="row">
	<div class="col">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="{% url 'cliente:credcoop_decision' %}">Cliente</a></li>
				<li class="breadcrumb-item active" aria-current="page">Credcoop</li>
			</ol>
		</nav>
	</div>
</div>

<h1 class="text-center mt-4 mb-4">CREDCOOP</h1>
<div class="">
    <div class="row">
        <div class="col-sm-6">
            <div class="card text-white bg-success mb-3">
                <div class="card-body">
                <h5 class="card-title">Cadastre um Cliente</h5> 
                {% comment %} <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>  {% endcomment %}
                <a href="#" class="btn btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#exampleModal">Cadastrar Cliente</a>
                </div>
            </div>
            </div>
        <div class="col-sm-6">
            <div class="card text-white bg-success mb-3">
                <div class="card-body">
                <h5 class="card-title">Cadastre um Fiador</h5>
                {% comment %} <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> {% endcomment %}
                <a href="{% url 'cliente:fiador_credcoop_add' %}" class="btn btn btn-primary btn-lg btn-block">Cadastrar Fiador</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel">O CLIENTE JÁ POSSUI FIADOR CADASTRADO?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span class="pull-center">
                        <a href="{% url 'cliente:credcoop_add' %}" type="button" class="btn btn-success">SIM</a>
                        <a href="{% url 'cliente:fiador_credcoop_add' %}" type="button" class="btn btn-danger">NÃO</a>
                    </span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>                   
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

projeto/cliente/templates/credcoop_delete.html
{% extends 'base.html' %}

{% block content %}

<h2>Tem certeza que quer deletar: {{ object }}</h2>

<div class="row">   
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Sim">
            <a href="{% url 'cliente:credcoop_cliente_list' %}" class="btn btn-primary">Não</a>
        </form>
    </div>
</div>

{% endblock content %}